spring:
  profiles:
    active: '@environment@'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


# 自行创建application-dev.yml、application-prod.yml
# 参考如下
# 开发环境配置
#springdoc:
#  paths-to-match: /api/**
#  swagger-ui:
#    operations-sorter: alpha
#spring:
#  mail:
#    host:
#    username:
#    password:
#  rabbitmq:
#    addresses:
#    username:
#    password:
#    virtual-host:
#  datasource:
#    url:
#    username:
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  security:
#    jwt:
#      key: 'abcdefghijklmn'
#      expire: 72
#      limit:
#        base: 10
#        upgrade: 300
#        frequency: 30
#    filter:
#      order: -100
#  web:
#    verify:
#      mail-limit: 60
#    flow:
#      period: 3
#      limit: 50
#      block: 30
#    cors:
#      origin: '*'
#      credentials: false
#      methods: '*'
#  minio:
#    endpoint:
#    username:
#    password:
#  weather:
#    key: #和风天气key
#
#
